### ISSUE TITLE
Loading Session

### ISSUE THREAD

**Issue by ViVers** [XMadMax/codeigniter-3-with-xhmvc#1]
Loading of session gives -> Unable to locate the specified class: Session.php

**Comment by XXPerez** [comment]
Vivers:  

Session is now a driver, must to be loaded as is : 

In autoload.php:
$autoload['drivers'] = array('session');

In any controller:
$this->load->driver('Session');

**Comment by ViVers** [comment]
Same error with driver autoload. When i delete in apps/core (extened libraries) it works properly so must be problem with MX loader. 

Edit: according log class has been initialized
(INFO - 16-02-2016 14:37:54 --> Session: Class initialized using 'files' driver.)
but it show still same error -> Unable to locate the specified class: Session.php

**Comment by XXPerez** [comment]
Yep, seems a problem with lower/upper case in Linux.

I'm finding solution for this.

**Comment by ViVers** [comment]
It looks like problem with $_classes register. I manualy override this with if statment and it works now. But i don't know much CI Core so i have no idea where can be problem.

i use this now in common.php
`if($class == 'Session')
        {
            return $_classes[$class];
        }`

**Comment by XXPerez** [comment]
Yes, it's a problem with drivers and MX, I wil find a solution mean while...

You must to create a MY_Session.php file under apps/base/application/libraries, extending from CI_Session to be fully compatible with HMVC:

<?php
class MY_Session extends CI_Sessio {}

**Comment by ViVers** [comment]
Your solution doesn't work. It tells me secondary initialization of session. For while i stick with my "little trick" if i find solution i will post it :)

**Comment by XXPerez** [comment]
Both solutins implemented... check the code, sync with repository.

Thans again for alert me on this problem !!

**Comment by ViVers** [comment]
You are welcome, your project helped me a lot to create good file structure and use with multiple application system, but there must be solution to avoid interfere with CI core. It sould be intact. 

I will dig more to core to find solution :)

**Comment by XXPerez** [comment]
I will try to dig also in a 'clean' solution.

Please, take care: module name must to be 'lowercase',

**Comment by ViVers** [comment]
I found out, this problem is related somehow because library is in subdirectory. I created my own library Rbac and put it to subdirectory 'Rbac/Rbac.php' and it shows same error.

**Comment by XXPerez** [comment]
Helo Vivers, try las modifications, I tested and Session and other drivers are loaded OK.

**Comment by ViVers** [comment]
Perfect  job ;) Thank You very much... I started agian with programming few days ago after long break... So this was little big nut for me :D

**Comment by XXPerez** [comment]
Helo, solved Session problems, library driver problems, there was also a problem loading common/modules.
Now working and HMVC, with minimal changes in Codeigniter.php, lines 402 to 423 that I will copy to next CI version.
