### ISSUE TITLE
Update to 3.0.6

### ISSUE THREAD

**Issue by ViVers** [XMadMax/codeigniter-3-with-xhmvc#3]
Hello, i updated for 3.0.6 for security reasons and it is not working any more :/ it loads modul normaly but not controller in controllers folrder in main app folder. 

it shows me "404 Page Not Found"

**Comment by XXPerez** [comment]
Helo Joel:

Few changes must to be done in Codeigniter.php:

Change lines 377 to 500 (aprox), full Sanity check block:

/*
- ------------------------------------------------------
-  Sanity checks
- ------------------------------------------------------
  *
-  The Router class has already validated the request,
-  leaving us with 3 options here:
  *
- 1) an empty class name, if we reached the default
-   controller, but it didn't exist;
- 2) a query string which doesn't go through a
-   file_exists() check
- 3) a regular request for a non-existing page
  *
-  We handle all of these as a 404 error.
  *
-  Furthermore, none of the methods in the app controller
-  or the loader class can be called via the URI, nor can
-  controller methods that begin with an underscore.
  */

$e404 = FALSE;
$class = ucfirst($RTR->class);
$method = $RTR->method;

if (empty($class))
{
$e404 = TRUE;
}
else
{
            if
(file_exists(APPPATH.'controllers/'.$RTR->directory.$class.'.php'))
            {

require_once(APPPATH.'controllers/'.$RTR->directory.$class.'.php');
            }
            elseif
(file_exists(COMMONPATH.'controllers/'.$RTR->directory.$class.'.php'))
            {

require_once(COMMONPATH.'controllers/'.$RTR->directory.$class.'.php');
            }
            else
            {
                $e404 = TRUE;
            }
        }

if (!$e404)
{
if ( ! class_exists($class, FALSE) OR $method[0] === '_' OR
method_exists('CI_Controller', $method))
{
$e404 = TRUE;
}
elseif (method_exists($class, '_remap'))
{
$params = array($method, array_slice($URI->rsegments, 2));
$method = '_remap';
}
// WARNING: It appears that there are issues with is_callable() even in PHP
5.2!
// Furthermore, there are bug reports and feature/change requests related
to it
// that make it unreliable to use in this context. Please, DO NOT change
this
// work-around until a better alternative is available.
elseif ( ! in_array(strtolower($method), array_map('strtolower',
get_class_methods($class)), TRUE))
{
$e404 = TRUE;
}
}

if ($e404)
{
if ( ! empty($RTR->routes['404_override']))
{
if (sscanf($RTR->routes['404_override'], '%[^/]/%s', $error_class,
$error_method) !== 2)
{
$error_method = 'index';
}

$error_class = ucfirst($error_class);

if ( ! class_exists($error_class, FALSE))
{
if (file_exists(APPPATH.'controllers/'.$RTR->directory.$error_class.'.php'))
{
require_once(APPPATH.'controllers/'.$RTR->directory.$error_class.'.php');
$e404 = ! class_exists($error_class, FALSE);
}
// Were we in a directory? If so, check for a global override
elseif ( ! empty($RTR->directory) &&
file_exists(APPPATH.'controllers/'.$error_class.'.php'))
{
require_once(APPPATH.'controllers/'.$error_class.'.php');
if (($e404 = ! class_exists($error_class, FALSE)) === FALSE)
{
$RTR->directory = '';
}
}
}
else
{
$e404 = FALSE;
}
}

// Did we reset the $e404 flag? If so, set the rsegments, starting from
index 1
if ( ! $e404)
{
$class = $error_class;
$method = $error_method;

$URI->rsegments = array(
1 => $class,
2 => $method
);
}
else
{
show_404($RTR->directory.$class.'/'.$method);
}
}

if ($method !== '_remap')
{
$params = array_slice($URI->rsegments, 2);
}

/*
- ------------------------------------------------------
-  Is there a "pre_controller" hook?
- ------------------------------------------------------
  */

## Xavier

_www.4amics.com http://www.4amics.com_

2016-06-15 21:24 GMT+02:00 JoellSVK notifications@github.com:

**Comment by ViVers** [comment]
THX :) New version of CI is out... Just let you know :)

**Comment by XXPerez** [comment]
Thanks Joell, I will update the project with this version.

## Xavier

_www.4amics.com http://www.4amics.com_

2016-07-27 18:50 GMT+02:00 JoellSVK notifications@github.com:

**Comment by XXPerez** [comment]
Upgrade to 3.1.0
